/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WsHelloworld {
    }
}
declare global {
    interface HTMLWsHelloworldElement extends Components.WsHelloworld, HTMLStencilElement {
    }
    var HTMLWsHelloworldElement: {
        prototype: HTMLWsHelloworldElement;
        new (): HTMLWsHelloworldElement;
    };
    interface HTMLElementTagNameMap {
        "ws-helloworld": HTMLWsHelloworldElement;
    }
}
declare namespace LocalJSX {
    interface WsHelloworld {
    }
    interface IntrinsicElements {
        "ws-helloworld": WsHelloworld;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ws-helloworld": LocalJSX.WsHelloworld & JSXBase.HTMLAttributes<HTMLWsHelloworldElement>;
        }
    }
}
