/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppkitHelloworld {
    }
}
declare global {
    interface HTMLAppkitHelloworldElement extends Components.AppkitHelloworld, HTMLStencilElement {
    }
    var HTMLAppkitHelloworldElement: {
        prototype: HTMLAppkitHelloworldElement;
        new (): HTMLAppkitHelloworldElement;
    };
    interface HTMLElementTagNameMap {
        "appkit-helloworld": HTMLAppkitHelloworldElement;
    }
}
declare namespace LocalJSX {
    interface AppkitHelloworld {
    }
    interface IntrinsicElements {
        "appkit-helloworld": AppkitHelloworld;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "appkit-helloworld": LocalJSX.AppkitHelloworld & JSXBase.HTMLAttributes<HTMLAppkitHelloworldElement>;
        }
    }
}
